### ISSUE TITLE
Ideas and discussion

### ISSUE THREAD

**Issue by duttakapil** [coderplex/teaching-kids-code#1]
Share yours ideas for the Teaching Python course we intend to take for the teachers of Oakridge Hyderabad

**Comment by Madhu94** [comment]
### Curriculum 
#### Students
- Basics of programming - input, output, variables, constants, looping and control
- Solving simple math problems with python - like quadratic equations, simultaneous equations.
- Some basic plots with matplotlib? - I believe they would have learnt histograms, "linear pairs", intersecting lines, etc, by now.  
- Using python documentation to look up what they might need in the standard library - I think we should have some exercises that involve the student searching the docs too.

#### Teachers
We can teach them all the above and also add how Python can help in teaching
- nbgrader to set assignments
- Using tools like Dash to create simple interactive science/math demos 

#### Some questions
- Would nteract be a better tool for teaching this? Instead of jupyter notebook which requires a command line.

**Comment by Niveshkrishna** [comment]
Also some 'introduction to Git' as well for teachers?
Basic flow
1. General overview of computers, information processing, technologies and various stacks.
2. Python overview: Python in web, Python in games, Python in ML and data analysis, etc. What frameworks to be used for a specific task.
3. Syntax and semantics: Variables, operators, lists, dictionaries, classes etc.
 
Will add more soon

**Comment by duttakapil** [comment]
Both of your comments look good @Madhu94 and @Niveshkrishna. 

Just to create some context, these teachers are not trying to become Python developers. Their only intention is to learn as much as is needed to teach their kids in school, at the level of grade 5 and 6. Post which, the kids will go ahead and continue learning in later classes. So we should be very careful with how much we try to stuff into our curriculum. 

Also, it appears that timeline wise, we will have to cover all of this over 3-4 weekends (both Saturday and Sunday) within a few hours. The teachers work from Monday to Saturday. They will have to come down to the school especially for these classes that we'll take. 

Also, regarding the kids, we wouldn't be teaching them directly as of now. We can take a 1 or 2 day workshop with them, but right now we'll only be teaching the teachers. We can also advice and help these teachers create their curriculum for the kids. 

It's really important to keep in our mind what their current level of understanding CS and Python is, and also what is their intention / motivation

**Comment by kv-cache** [comment]
It's also important for us to ensure that they understand the fundamentals of programming, how things work under the hood. Because these teachers will go on and teach kids how to program. We should all understand that there is a very big responsibility on us. Making sure that they understand what programming really is about is very important. It's also important to emphasize on the creativity side of programming.

**Comment by duttakapil** [comment]
We should stress on programming as a tool to solve problems and build things, just like one would use paint to create art. We should show examples of day-to-day problems being solved with code, if we can. We could take a approach similar to CS50 in introducing Python. I agree with @VineethKanaparthi, we should try to explain the fundamentals of the code, what's happening under the hood

**Comment by Madhu94** [comment]
> We should show examples of day-to-day problems being solved with code, if we can. 

This was my intention when I suggested that we could start by coding what they learn in theory, in their classrooms. As an ECE student, I understood Fourier Series only when someone explained it to me with some code and a plot - adding sine waves one by one to create a complicated waveform. I tried to do the same thing with what  the students would be studying in 5th and 6th - basic stats and algebra.

**Comment by duttakapil** [comment]
Yeah, that makes sense @Madhu94. It gives them some relevance. I guess we should not just talk to the CS teachers, but also the Math teachers at the school then? It would be great if you could join us at the meeting on Monday. But I know you will have office

**Comment by Madhu94** [comment]
Yeah, I can't come :-/  But I think CS teachers can handle this though? They would already be good with basic programming and just need to find out what is relevant to the kids and show them how to map theory to code.

**Comment by Rohithgilla12** [comment]
Well all ideas and everything is much wow!!
I would like to add a basic thing, we should not introduce IDE's and stuff. 
Just with some text editors and terminal/command prompt to run the scripts.
What do you say?

**Comment by Madhu94** [comment]
I had a contrasting opinion to @Rohithgilla12 :) I felt the command-line might overwhelm at such an early stage. For Python, what does everyone think of [nteract](https://github.com/nteract/nteract/) ?

**Comment by Rohithgilla12** [comment]
Then we can go with the "IDLE" the default thing which we get with python installation.
Nteract is also really good

**Comment by Madhu94** [comment]
IDLE sounds good.
